import { prisma } from "../src/shared/lib/prisma";

async function seed() {
    await prisma.course.createMany({
        data: [
            //! semestre 1
            {
                code: "CC0001",
                name: "INTRODUÇÃO À PROGRAMAÇÃO",
                semesterLevel: 1,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0002",
                name: "CÁLCULO DIFERENCIAL E INTEGRAL I",
                semesterLevel: 1,
                credits: 6,
                type: "REQUIRED",
            },
            {
                code: "CC0004",
                name: "ÁLGEBRA VETORIAL E GEOMETRIA ANALÍTICA",
                semesterLevel: 1,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0005",
                name: "FUNDAMENTOS DE MATEMÁTICA DISCRETA",
                semesterLevel: 1,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0015",
                name: "CIRCUITOS DIGITAIS",
                semesterLevel: 1,
                credits: 4,
                type: "REQUIRED",
            },

            //! semestre 2
            {
                code: "CC0007",
                name: "CÁLCULO DIFERENCIAL E INTEGRAL II",
                semesterLevel: 2,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0020",
                name: "ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES",
                semesterLevel: 2,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0061",
                name: "ALGORITMOS E ESTRUTURAS DE DADOS",
                semesterLevel: 2,
                credits: 6,
                type: "REQUIRED",
            },
            {
                code: "CC0062",
                name: "LABORATÓRIO DE ALGORITMOS E ESTRUTURAS DE DADOS",
                semesterLevel: 2,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0063",
                name: "ÁLGEBRA LINEAR",
                semesterLevel: 2,
                credits: 4,
                type: "REQUIRED",
            },

            //! semestre 3
            {
                code: "CC0017",
                name: "ALGORITMOS EM GRAFOS",
                semesterLevel: 3,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0018",
                name: "CÁLCULO NUMÉRICO",
                semesterLevel: 3,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0019",
                name: "PROGRAMAÇÃO ORIENTADA A OBJETOS",
                semesterLevel: 3,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0026",
                name: "SISTEMAS OPERACIONAIS",
                semesterLevel: 3,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0064",
                name: "LÓGICA PARA CIÊNCIA DA COMPUTAÇÃO",
                semesterLevel: 3,
                credits: 4,
                type: "REQUIRED",
            },

            //! semestre 4
            {
                code: "CC0010",
                name: "PROBABILIDADE E ESTATÍSTICA",
                semesterLevel: 4,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0022",
                name: "FUNDAMENTOS DE LINGUAGENS DE PROGRAMAÇÃO",
                semesterLevel: 4,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0024",
                name: "REDES DE COMPUTADORES",
                semesterLevel: 4,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0025",
                name: "BANCO DE DADOS",
                semesterLevel: 4,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0065",
                name: "CONSTRUÇÃO E ANÁLISE DE ALGORITMOS",
                semesterLevel: 4,
                credits: 4,
                type: "REQUIRED",
            },

            //! semestre 5
            {
                code: "CC0029",
                name: "COMPUTAÇÃO GRÁFICA",
                semesterLevel: 5,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0030",
                name: "ENGENHARIA DE SOFTWARE",
                semesterLevel: 5,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0044",
                name: "LABORATÓRIO DE REDES",
                semesterLevel: 5,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0066",
                name: "AUTÔMATOS E LINGUAGENS FORMAIS",
                semesterLevel: 5,
                credits: 4,
                type: "REQUIRED",
            },

            //! semestre 6
            {
                code: "CC0027",
                name: "INTELIGÊNCIA ARTIFICIAL",
                semesterLevel: 6,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0032",
                name: "COMPILADORES",
                semesterLevel: 6,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0042",
                name: "SISTEMAS DISTRIBUÍDOS",
                semesterLevel: 6,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0067",
                name: "TEORIA DA COMPUTAÇÃO",
                semesterLevel: 6,
                credits: 4,
                type: "REQUIRED",
            },
            {
                code: "CC0068",
                name: "COMPUTAÇÃO, ÉTICA E SOCIEDADE",
                semesterLevel: 6,
                credits: 2,
                type: "REQUIRED",
            },


            //* optativas
            {
                code: "CC0003",
                name: "INTRODUÇÃO À CIÊNCIA DA COMPUTAÇÃO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0008",
                name: "FUNDAMENTOS DE MECÂNICA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0013",
                name: "CÁLCULO VETORIAL",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0014",
                name: "FUNDAMENTOS DE ELETROMAGNETISMO",
                semesterLevel: 0,
                credits: 6,
                type: "ELECTIVE",
            },
            {
                code: "CC0016",
                name: "LABORATÓRIO DE PROGRAMAÇÃO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0021",
                name: "PROGRAMAÇÃO CONCORRENTE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0033",
                name: "PROJETO DE GRADUAÇÃO 1 TCC",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0035",
                name: "PROJETO DE GRADUAÇÃO II TCC",
                semesterLevel: 0,
                credits: 6,
                type: "ELECTIVE",
            },
            {
                code: "CC0036",
                name: "ANÁLISE E PROJETO DE SISTEMAS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0037",
                name: "INTERFACE HUMANO COMPUTADOR",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0038",
                name: "PROGRAMAÇÃO PARA WEB",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0039",
                name: "GERÊNCIA DE PROJETOS E QUALIDADE DE SOFTWARE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0040",
                name: "VERIFICAÇÃO E VALIDAÇÃO DE SOFTWARE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0043",
                name: "PROGRAMAÇÃO PARA DISPOSITIVOS MÓVEIS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0045",
                name: "PROJETO DE REDES DE COMPUTADORES",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0046",
                name: "REDES CONVERGENTES",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0047",
                name: "AVALIAÇÃO DE DESEMPENHO DE REDES",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0048",
                name: "REDES SEM FIO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0049",
                name: "SEGURANÇA DE REDES",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0050",
                name: "PRINCÍPIOS DE DESENVOLVIMENTO WEB",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0051",
                name: "APRENDIZADO DE MÁQUINA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0052",
                name: "INTRODUÇÃO À ANÁLISE DE DADOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0053",
                name: "MINERAÇÃO DE DADOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0055",
                name: "RECUPERAÇÃO DA INFORMAÇÃO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0056",
                name: "PROCESSAMENTO DE LINGUAGEM NATURAL",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0057",
                name: "INTRODUÇÃO À TEORIA DOS JOGOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0059",
                name: "TÓPICOS AVANÇADOS EM ENGENHARIA DE SOFTWARE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0060",
                name: "TEORIA DOS GRAFOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0069",
                name: "ALGORITMOS APROXIMATIVOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0070",
                name: "OTIMIZAÇÃO COMBINATÓRIA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0071",
                name: "PESQUISA OPERACIONAL",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0072",
                name: "GEOMETRIA COMPUTACIONAL",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0073",
                name: "PROGRAMAÇÃO LINEAR",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0074",
                name: "PROGRAMAÇÃO FUNCIONAL",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0075",
                name: "PROGRAMAÇÃO PARALELA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0076",
                name: "ARQUITETURA DE COMPUTADORES DE ALTO DESEMPENHO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0077",
                name: "AVALIAÇÃO DE DESEMPENHO DE SISTEMAS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0078",
                name: "MÉTODOS FORMAIS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0079",
                name: "PROJETO DE SISTEMAS DE BANCO DE DADOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0080",
                name: "COMPUTAÇÃO EVOLUTIVA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0081",
                name: "SISTEMAS MULTIAGENTES",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0082",
                name: "WEB SEMANTICA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0083",
                name: "PROCESSAMENTO DE IMAGENS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0084",
                name: "EMPREENDEDORISMO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0085",
                name: "ANÁLISE MULTIVARIADA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0086",
                name: "MODELAGEM E SIMULAÇÃO DE SISTEMAS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0087",
                name: "INFERÊNCIA ESTATÍSTICA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0088",
                name: "TÉCNICAS DE AMOSTRAGEM",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0089",
                name: "PROCESSOS ESTOCÁSTICOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0090",
                name: "SIMULAÇÃO ESTOCÁSTICA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0091",
                name: "ANÁLISE DE REGRESSÃO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0092",
                name: "SÉRIES TEMPORAIS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0093",
                name: "CONTROLE ESTATÍSTICO DE QUALIDADE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0094",
                name: "INGLÊS TÉCNICO CIENTÍFICO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0095",
                name: "TÓPICOS AVANÇADOS EM COMPLEXIDADE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0096",
                name: "TÓPICOS AVANÇADOS EM ALGORITMOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0097",
                name: "PROJETO DE DESENVOLVIMENTO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0098",
                name: "RACIOCÍNIO AUTOMATIZADO VIA LÓGICA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0099",
                name: "METODOLOGIA CIENTÍFICA PARA CIÊNCIA DA COMPUTAÇÃO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0100",
                name: "INTRODUÇÃO A DESIGN DE JOGOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0101",
                name: "FUNDAMENTOS DE SENSORES INTELIGENTES PARA INDUSTRIA",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0102",
                name: "RELAÇÕES ÉTNICO RACIAIS E AFRICANIDADES",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0103",
                name: "LÍNGUA BRASILEIRA DE SINAIS (LIBRAS)",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0104",
                name: "PROCESSOS DE SOFTWARE E GESTÃO ÁGIL",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0105",
                name: "ENGENHARIA DE REQUISITOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0106",
                name: "GERÊNCIA DE CONFIGURAÇÃO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0107",
                name: "TESTE DE SOFTWARE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0108",
                name: "EXPERIMENTAÇÃO EM ENGENHARIA DE SOFTWARE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0109",
                name: "ARQUITETURA DE SOFTWARE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0110",
                name: "QUALIDADE E MANUTENÇÃO DE SOFTWARE",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0111",
                name: "ENGENHARIA DE SOFTWARE PARA WEB",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0112",
                name: "CARREIRA, NEGÓCIOS E SOFT SKILLS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0113",
                name: "SISTEMAS DE INFORMAÇÃO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0114",
                name: "GOVERNANÇA DE TI E GESTÃO DO CONHECIMENTO",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
            {
                code: "CC0115",
                name: "SISTEMAS COLABORATIVOS",
                semesterLevel: 0,
                credits: 4,
                type: "ELECTIVE",
            },
        ],
        skipDuplicates: true
    });
}

seed()
    .then(() => {
        console.log("Database seeded!");
    })
    .catch((e) => {
        console.error(e);
    })
    .finally(() => {
        prisma.$disconnect();
    });
